import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { Routes } from '../routes';
import styles from '../styles/Home.module.css';

const Detail: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to detail page</h1>
        <Link href={Routes.Home()}>
          <a>Home</a>
        </Link>
      </main>
    </div>
  );
};

export default Detail;
